mod.addBlock("meatchunkBlock.js", "normal");
mod.addBlock("meatWood.js", "normal");
mod.addBlock("meatLeaf.js", "normal");
mod.addBlock("taintedWood.js", "normal");
mod.addBlock("deadWood.js", "normal");
mod.addBlock("OverworldLeaves.js", "normal");
mod.addBlock("overworldtrees.js", "normal");
mod.addBlock("SpecialOres.js", "normal");
mod.addBlock("InfiniOres.js", "normal");
mod.addBlock("specialingredBs.js", "normal");
mod.addItem("silvernugget.js", "normal");
mod.addItem("specialnuggets.js", "normal");
mod.addItem("woodchunk.js", "normal");
mod.addItem("Irium Axe.js", "normal");
mod.addItem("POre.js", "normal");
mod.addItem("Netherstarforms.js", "normal");
mod.addItem("specialingredIs.js", "normal");
mod.addItem("OreJ.js", "normal");
mod.addToOreDictionary( "oreInfinium", "BanjoPackAlpha:InfiniXores:0" );
mod.addToOreDictionary( "oreClustHoDU", "BanjoPackAlpha:InfiniXores:1" );
mod.addToOreDictionary( "oreClustHoD1", "BanjoPackAlpha:InfiniXores:2" );
mod.addToOreDictionary( "oreClustHoD2", "BanjoPackAlpha:InfiniXores:3" );
mod.addToOreDictionary( "oreClustHoD3", "BanjoPackAlpha:InfiniXores:4" );
mod.addToOreDictionary( "oreClustHeart", "BanjoPackAlpha:banjoOres:0" );
mod.addToOreDictionary( "oreClustBizz1", "BanjoPackAlpha:banjoOres:1" );
mod.addToOreDictionary( "oreClustBizz2", "BanjoPackAlpha:banjoOres:2" );
mod.addToOreDictionary( "oreClustEye", "BanjoPackAlpha:banjoOres:3" );
mod.addToOreDictionary( "oreClustDark1", "BanjoPackAlpha:banjoOres:4" );
mod.addToOreDictionary( "oreClustDark2", "BanjoPackAlpha:banjoOres:5" );
mod.addToOreDictionary( "oreClustIce1", "BanjoPackAlpha:banjoOres:6" );
mod.addToOreDictionary( "oreClustIce2", "BanjoPackAlpha:banjoOres:7" );
mod.addToOreDictionary( "oreClustIce3", "BanjoPackAlpha:banjoOres:8" );
mod.addToOreDictionary( "oreClustIce4", "BanjoPackAlpha:banjoOres:9" );
mod.addToOreDictionary( "oreClustIce5", "BanjoPackAlpha:banjoOres:10" );
mod.addToOreDictionary( "oreClustObsid1", "BanjoPackAlpha:banjoOres:11" );
mod.addToOreDictionary( "oreClustObsid2", "BanjoPackAlpha:banjoOres:12" );
mod.addToOreDictionary( "oreClustObsid3", "BanjoPackAlpha:banjoOres:13" );
mod.addToOreDictionary( "oreClustObsid4", "BanjoPackAlpha:banjoOres:14" );
mod.addWorldGen("Infiniore1.js", "ore");
mod.addWorldGen("Infiniore2.js", "ore");
mod.addWorldGen("Infiniore3.js", "ore");
mod.addWorldGen("Infiniore4.js", "ore");
mod.addWorldGen("Infiniore5.js", "ore");
mod.addWorldGen("Infiniore6.js", "ore");
mod.addWorldGen("Infiniore7.js", "ore");
mod.addWorldGen("Infiniore8.js", "ore");
mod.addWorldGen("Infiniore9.js", "ore");
mod.addWorldGen("Infiniore10.js", "ore");
mod.addWorldGen("Infiniore11.js", "ore");